ingest: Add CI build config
The ingest workflow current runs in <1 minute so I figured it'd be nice
to add as an additional check in the GH Action CI workflow.
If the ingest workflow ever runs for too long, we should figure out a
way to subset the ingest data.

The CI build config includes a bogus key because Snakemake requires the
config file to have at least one top level key.

Previous CI run without the bogus key ran into an error¹
```
snakemake.exceptions.WorkflowError: Config file must be given as JSON or YAML with keys at top level.
```

¹ <https://github.com/nextstrain/zika/actions/runs/9948628997/job/27483549394#step:9:17>